"""initial schema

Revision ID: 3d2a99835067
Revises: 
Create Date: 2026-07-10 15:33:17.550536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2a99835067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('avg_dwell', sa.Float(), nullable=True),
    sa.Column('avg_flight', sa.Float(), nullable=True),
    sa.Column('std_dwell', sa.Float(), nullable=True),
    sa.Column('std_flight', sa.Float(), nullable=True),
    sa.Column('backspace_rate', sa.Float(), nullable=True),
    sa.Column('longest_pause', sa.Float(), nullable=True),
    sa.Column('dwell_flight_ratio', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('rule_anomaly', sa.Boolean(), nullable=True),
    sa.Column('ml_anomaly', sa.Boolean(), nullable=True),
    sa.Column('true_label', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_is_anomaly'), ['is_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_true_label'), ['true_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_true_label'))
        batch_op.drop_index(batch_op.f('ix_sessions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sessions_is_anomaly'))

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
